ALTER TABLE [dbo].[PRETAnswerXLaws]
    ADD CONSTRAINT [PK_PRETAnswerXLaws] PRIMARY KEY CLUSTERED ([AnswerId] ASC, [LawId] ASC, [GroupId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

