ALTER TABLE [dbo].[ProjectWorkers]
    ADD CONSTRAINT [PK_ProjectWorkers_1] PRIMARY KEY CLUSTERED ([UserId] ASC, [ProjectId] ASC, [RoleId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

