<%@ Page Title="" Language="C#" MasterPageFile="~/Views/Shared/Site.Master" Inherits="System.Web.Mvc.ViewPage<dynamic>" %>

<asp:Content ID="Content1" ContentPlaceHolderID="TitleContent" runat="server">
	SecurityStep3
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">

    <div class="section-container">

        <div class="section-header">
        
            <div class="col1">
                <h2>Security Step 3 - Develop Artifacts</h2>
            </div>
            <div class="col2">
            </div>

        </div>    

        <div class="section-contents">
            <p>
                Before the requirements engineering team and stakeholders can generate a comprehensive set
                of security requirements, the team must collect a complete set of artifacts of the system. The
                following are the types of artifacts that should be collected:
            </p>

            <ul>
                <li>system architecture diagrams</li>
                <li>use case scenarios/diagrams</li>
                <li>misuse case scenarios/diagrams</li>
                <li>attack trees</li>
                <li>standardized templates and forms</li>
            </ul>

            <p>
                In developing such artifacts, it is important to enlist the assistance of knowledgeable engineers
                from the organization. In some cases, it is possible that the client organization will not
                have any of the artifacts in place, including such basic items as system architecture diagrams.
                In such situations, the requirements engineering team should reiterate to the stakeholders that
                by creating and documenting artifacts of the system, they are investing in the success of the
                project.            
            </p>

        </div>

    </div>

    <div class="section-container">
    
        <div class="section-header"><h3>Responsibilities</h3></div>

        <div class="section-contents">
        
            <h3>Requirements Engineering Team</h3>

                <p>
                    Work with the stakeholders and client organization to identify and collect as many artifacts as
                    possible.
                </p>

            <h3>Stakeholders</h3>

                <p>
                    Generate or collect any system artifacts and present them to the requirements engineering
                    team. This information includes system architectures, actors, use/misuse cases, and suspected
                    attacks. It is possible that other experts from within the organization may be called upon to
                    provide information as well.                
                </p>

            <h3>Joint</h3>

                <p>
                    Verify the accuracy and completeness of all artifacts.
                </p>
        </div>

    </div>

    <div class="section-container">
    
        <div class="section-header"><h3>Exit Criteria</h3></div>

        <div class="section-contents">
        
            <p>
                A set of artifacts for the system, as complete as possible, has been generated by the requirements
                engineering team and shared with the stakeholders.
            </p>
        
        </div>

    </div>

</asp:Content>

<asp:Content ID="Content3" ContentPlaceHolderID="ScriptContent" runat="server">
</asp:Content>

<asp:Content ID="Content4" ContentPlaceHolderID="NavContents" runat="server">
<a href="#" onClick="history.go(-1)" class="nav-button">Back</a> 
</asp:Content>
